# Generated by Django 5.2.11 on 2026-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='puntos',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='PerfilEmpleado',
        ),
    ]
