# Generated by Django 5.2.11 on 2026-03-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alertaseguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True, help_text='Contenido en texto o descripción de la imagen.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/slides/')),
                ('orden', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='principal.curso')),
            ],
            options={
                'verbose_name_plural': 'Contenidos de Curso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='principal.curso')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='principal.pregunta')),
            ],
            options={
                'verbose_name_plural': 'Opciones',
            },
        ),
    ]
