# Generated by Django 5.2.11 on 2026-03-13 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_contenidocurso_pregunta_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='cursos/materiales/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='principal.curso')),
            ],
            options={
                'verbose_name_plural': 'Materiales de Curso',
            },
        ),
    ]
