# Generated by Django 5.2.11 on 2026-03-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_materialcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidocurso',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='cursos/slides/'),
        ),
    ]
