# Generated by Django 5.2.11 on 2026-03-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_contenidocurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
