# Generated by Django 5.2.11 on 2026-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_perfil_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocurso',
            name='ultima_pagina',
            field=models.IntegerField(default=0),
        ),
    ]
