# Generated by Django 5.2.11 on 2026-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_progresocurso_ultima_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cursos/videos/'),
        ),
    ]
