# Generated by Django 5.2.11 on 2026-03-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_curso_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='bi-shield-shaded', max_length=50)),
                ('puntos', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'Simulaciones',
            },
        ),
        migrations.CreateModel(
            name='DesafioSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='simulaciones/')),
                ('texto_complementario', models.TextField(blank=True, help_text='Texto opcional para dar contexto al desafío.')),
                ('es_peligro', models.BooleanField(default=False, help_text='¿Es una amenaza real?')),
                ('explicacion', models.TextField(help_text='Explicación que se mostrará al usuario como feedback.')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='principal.simulacion')),
            ],
            options={
                'verbose_name_plural': 'Desafíos de Simulación',
            },
        ),
        migrations.CreateModel(
            name='ProgresoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_simulaciones', to=settings.AUTH_USER_MODEL)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.simulacion')),
            ],
            options={
                'verbose_name_plural': 'Progresos de Simulaciones',
                'unique_together': {('usuario', 'simulacion')},
            },
        ),
    ]
