# Generated by Django 5.2.11 on 2026-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_simulacion_desafiosimulacion_progresosimulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
