# Generated by Django 5.2.11 on 2026-05-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_perfil_nombre_empresa_perfil_notas_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
